<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-484</name>
   <tag></tag>
   <elementGuidId>78e11f73-ae6e-4b30-bb98-c17a7f410622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-484</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-484']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c231b986-75d4-4f8a-beeb-844f36e77af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-484</value>
      <webElementGuid>22af73c9-62d9-4691-b790-05a0888b1d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08d09337-47dc-425d-8bbe-38ae07be19ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-484&quot;)</value>
      <webElementGuid>1a7a34c4-972c-45d7-8705-55c4d72b499d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-484']</value>
      <webElementGuid>b0db50b9-ffcb-4651-8d0d-bb39db419f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>47f8b0e2-31ac-4ad9-9242-29974164a239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>da253edd-b5d0-4d27-95da-a53f851ea65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-484' and @type = 'text']</value>
      <webElementGuid>b38330f5-6d6e-4731-a1d8-5cab8df55fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
