<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap_input-481</name>
   <tag></tag>
   <elementGuidId>2ae161fa-d9ea-4726-ae76-82c82c26f4d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-481</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-481']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea18319-cb12-4e33-8227-e6c3d367e44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-481</value>
      <webElementGuid>f64db2e8-6302-4ae5-b6a8-40e0f3ed1dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5955c5b-c337-4f95-b2aa-8b5d8ab63f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-481&quot;)</value>
      <webElementGuid>0b765358-c241-43af-804a-f15384ded420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-481']</value>
      <webElementGuid>a618a4c4-1091-4ac1-b5ec-91ac6ced3052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>50a0486e-185d-4bc0-8abb-e09c591c06f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>acc9c033-041b-4e38-83d9-ebec959b5a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-481' and @type = 'text']</value>
      <webElementGuid>118428db-0186-44b1-acbc-9aac0ff6f792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
