<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-487</name>
   <tag></tag>
   <elementGuidId>e21e8029-f870-4459-a5de-0a2e583dc781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-487</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-487']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16755667-385c-47f1-87a8-601b652bad77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-487</value>
      <webElementGuid>6426819b-1bc2-4c19-a790-6ac33004f018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83789ac7-abfe-4a6f-a512-64c22cf20950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-487&quot;)</value>
      <webElementGuid>6e0bbd49-10eb-40e3-b1cc-f7fe91c3e0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-487']</value>
      <webElementGuid>a37929d9-f340-4d7d-bd59-894b30a34c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>54b733c6-1648-4902-9fc2-10da487307b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>cf1e19eb-62dc-4d67-9562-dce521409305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-487' and @type = 'text']</value>
      <webElementGuid>20a47022-062c-4661-90e5-a47e097c2071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
